version: '3'

services:
  api:
    build: ./studlabBackend
    ports:
      - "8080:8080"
    volumes:
      - ./studlabBackend:/code
    depends_on:
      - db
  db:
    image: mariadb:11.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: studlab
      MYSQL_USER: mattia
      MYSQL_PASSWORD: mattia
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - db

volumes:
  data:
